version: '3.3'

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.9-management-alpine
    hostname: rabbitmq
    networks:
      - root-cause-net
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./DockerVolumes/RabbitMQ/Setup/:/etc/rabbitmq/

  timescale:
    image: timescale/timescaledb:2.6.0-pg12
    container_name: "timescale"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "rootcause"
    networks:
      - root-cause-net
    ports:
      - "5432:5432"
    volumes:
      - ./DockerVolumes/TimeScale/Setup/DBinit:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana:8.4.2
    container_name: "grafana"
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - root-cause-net
    volumes:
      - ./DockerVolumes/Grafana/Setup/provisioning:/etc/grafana/provisioning
      - ./DockerVolumes/Grafana/Setup/dashboards:/var/lib/grafana/dashboards
      - ./DockerVolumes/Grafana/Setup/grafana.ini:/etc/grafana/grafana.ini
      - ./DockerVolumes/Nginx/certs:/var/ssl/certs/

  rootcause:
    build: .
    container_name: "RootCause"
    restart: always
    ports:
      - "${QUARKUS_PORT}:8081"
    depends_on:
          - "rabbitmq"
    networks:
      - root-cause-net
    environment:
      REPORT_EXPANDED: ${REPORT_EXPANDED}
      REPORT_NO_CACHE: ${REPORT_NO_CACHE}
      REPORT_DELTA: ${REPORT_DELTA}
      REPORT_PROXIMITY_LIMIT: ${REPORT_PROXIMITY_LIMIT}
      REPORT_NETWORK_SIZE: ${REPORT_NETWORK_SIZE}
      PROFILE: ${PROFILE}

  nginx:
    container_name: nginx
    image: nginx:1.21.6
    depends_on:
      - rootcause
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./DockerVolumes/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./DockerVolumes/Nginx/certs:/etc/nginx/certs
    networks:
      - root-cause-net

networks:
  root-cause-net:
    driver: bridge