version: '3.3'

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.9-management-alpine
    hostname: rabbitmq
    networks:
      - root-cause-net
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./DockerVolumes/RabbitMQ/Setup/:/etc/rabbitmq/

  timescale:
    image: timescale/timescaledb:latest-pg12
    container_name: "timescale"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "rootcause"
    networks:
      - root-cause-net
    ports:
      - "5432:5432"
    volumes:
      - ./DockerVolumes/TimeScale/Setup/DBinit:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - "3001:3000"
    networks:
      - root-cause-net
    volumes:
      - ./DockerVolumes/Grafana/Setup/provisioning:/etc/grafana/provisioning
      - ./DockerVolumes/Grafana/Setup/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "viewer"

  rootcause:
    build: .
    container_name: "RootCause"
    restart: always
    ports:
      - "80:8080"
    depends_on:
          - "rabbitmq"
    networks:
      - root-cause-net
    environment:
      DELTA: ${DELTA}
      PROXIMITY_LIMIT: ${PROXIMITY_LIMIT}
      NETWORK_SIZE: ${NETWORK_SIZE}

networks:
  root-cause-net:
    driver: bridge
