apiVersion: 1

datasources:
  - name: timescale
    type: postgres
    url: timescale:5432
    access: proxy
    user: root
    database: rootcause
    basicAuth: false
    isDefault: true
    jsonData:
      sslmode: disable
      timescaledb: true
      timeInterval: "5s"
    secureJsonData:
      password: root
    version: 1
    editable: true